/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogButton: typeof import('./src/components/buttons/DialogButton.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    EntityLayout: typeof import('./src/components/layouts/EntityLayout.vue')['default']
    EntityTable: typeof import('./src/components/tables/EntityTable.vue')['default']
    ErrorMessage: typeof import('./src/components/tables/fragments/ErrorMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    ViewGroupButton: typeof import('./src/components/buttons/ViewGroupButton.vue')['default']
  }
}
